$(function () {
  const app=$('#terminalInventoryApp'); if(!app.length)return;
  const types=JSON.parse(app.attr('data-types')),expected=JSON.parse(app.attr('data-expected-counts')||'{}');
  let active=JSON.parse(app.attr('data-active')||'[]'),requestKey=null,resolvedType=null,selectedCloseId=null,detailIncident=null;
  const modal=new bootstrap.Modal(document.getElementById('terminalIncidentModal'));
  const resolvedModal=new bootstrap.Modal(document.getElementById('terminalResolvedModal'));
  const detailModal=new bootstrap.Modal(document.getElementById('terminalTicketDetailModal'));
  const esc=value=>$('<div>').text(value??'').html();
  function safeAttachmentUrl(value){try{const url=new URL(String(value||''),window.location.origin);return ['http:','https:'].includes(url.protocol)?url.href:'';}catch(e){return '';}}
  function commenterLabel(comment){const values=[comment.user_name,comment.related_data?.user?.full_name,comment.user?.full_name,comment.author];for(const value of values){const name=String(value||'').trim();if(name&&!['usuario','user','requester','solicitante'].includes(name.toLocaleLowerCase('es-MX')))return name;}return comment.user_id?'Autor de Mojo #'+comment.user_id:'Autor sin identificar';}
  function detailSectionHeading(icon,kicker,title,extra=''){return '<div class="terminal-section-heading"><span class="terminal-section-icon" aria-hidden="true"><i class="fa fa-'+icon+'"></i></span><div><span class="terminal-section-kicker">'+esc(kicker)+'</span><h6>'+esc(title)+'</h6></div>'+(extra?'<span class="terminal-section-extra">'+extra+'</span>':'')+'</div>';}
  const stateLabel=value=>({Solved:'Resuelto',Abierta:'Abierto',Reabierta:'Reabierto',Closed:'Cerrado'})[value]||value||'Sin estado';
  function dateLabel(value){if(!value)return '';const raw=String(value);let date;if(/^\d{4}-\d{2}-\d{2}$/.test(raw)){const [year,month,day]=raw.split('-').map(Number);date=new Date(year,month-1,day);}else date=new Date(raw);if(Number.isNaN(date.getTime()))return raw;return new Intl.DateTimeFormat('es-MX',/^\d{4}-\d{2}-\d{2}$/.test(raw)?{dateStyle:'medium'}:{dateStyle:'medium',timeStyle:'short'}).format(date);}
  function cleanDescription(value){return String(value||'').replace(/<!--[\s]*terminal-request-[a-f0-9-]+[\s]*-->/gi,'').replace(/[\s→]+$/,'').trim();}
  function newRequestKey(){if(window.crypto?.randomUUID)return window.crypto.randomUUID();const bytes=new Uint8Array(16);if(window.crypto?.getRandomValues)window.crypto.getRandomValues(bytes);else for(let i=0;i<bytes.length;i++)bytes[i]=Math.floor(Math.random()*256);return Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('');}
  $('#printTerminalRegister').on('click',()=>window.print());
  function statusOf(i){return i.estado_local||i.estado_mojo||'Abierta';}
  function solvedFor(type){return active.filter(i=>i.tipo_terminal===type&&statusOf(i)==='Solved');}
  function openDetail(id){
    detailIncident=active.find(i=>Number(i.id)===Number(id)); if(!detailIncident)return;
    $('#ticketReplyForm').addClass('d-none')[0].reset();$('#ticketReplyFileNames').text('Ningún archivo seleccionado.');$('#ticketReplyError,#ticketReplyMode').addClass('d-none').empty();$('#ticketReplyMessage').prop('disabled',false);$('#ticketReplyTitle').text('Nuevo mensaje');
    $('#ticketDetailBody').html('<div class="terminal-detail-loading"><span class="spinner-border spinner-border-sm" role="status"></span> Cargando información y respuestas…</div>');
    $('#ticketDetailActions').empty(); detailModal.show();
    $.getJSON('/operations/terminal_incident_detail',{incident_id:id}).done(r=>{
      if(!r.success)throw new Error(r.message||'No fue posible cargar el ticket.');
      const i=r.incident,t=r.ticket,comments=r.comments||[],hist=r.state_history||[];
      const fields=[['Estación',i.station],['Solicitante',t.requester],['Técnico TI',t.assignee],['Prioridad',t.priority],['Apertura',dateLabel(t.created||i.opened)],['Última actualización',dateLabel(t.updated)],['Vencimiento',dateLabel(t.due)],['Serie',i.serial],['Folio proveedor',i.provider_folio],['Fecha de reporte',dateLabel(i.provider_date)]];
      $('#ticketDetailTitle').text('Ticket #'+Number(i.ticket_id)+' · '+(types[i.type]?.label||i.type));
      let html='<div class="terminal-ticket-hero"><div><span class="terminal-detail-kicker">'+esc(types[i.type]?.label||i.type)+'</span><h4>'+esc(t.title||cleanDescription(i.description)||'Incidencia de terminal')+'</h4><span class="terminal-ticket-state">'+esc(stateLabel(i.state))+'</span></div></div><div class="terminal-detail-grid">';
      fields.forEach(([label,value])=>{if(value)html+='<div><span>'+esc(label)+'</span><strong>'+esc(value)+'</strong></div>';});
      html+='</div><section class="terminal-detail-section terminal-info-card terminal-report-section">'+detailSectionHeading('file-alt','REPORTE','Descripción del problema')+'<div class="terminal-section-body terminal-report-copy"><p>'+esc(cleanDescription(i.description||t.description)||'Sin descripción.')+'</p></div></section>';
      if(t.resolution)html+='<section class="terminal-detail-section terminal-info-card terminal-resolution-section">'+detailSectionHeading('check-circle','CIERRE DEL TICKET','Resolución registrada')+'<div class="terminal-section-body"><p>'+esc(t.resolution)+'</p></div></section>';
      if(t.custom_fields?.length)html+='<section class="terminal-detail-section terminal-info-card">'+detailSectionHeading('list-alt','DETALLE','Información adicional')+'<div class="terminal-section-body"><dl class="terminal-detail-list">'+t.custom_fields.map(f=>'<div><dt>'+esc(f.label)+'</dt><dd>'+esc(f.value)+'</dd></div>').join('')+'</dl></div></section>';
      if(t.attachments?.length)html+='<section class="terminal-detail-section terminal-info-card">'+detailSectionHeading('paperclip','ARCHIVOS DEL TICKET','Documentos adjuntos')+'<div class="terminal-section-body"><ul class="terminal-ticket-attachments">'+t.attachments.map(f=>{const url=safeAttachmentUrl(f.url);return '<li>'+(url?'<a href="'+esc(url)+'" target="_blank" rel="noopener">'+esc(f.name)+'</a>':esc(f.name))+'</li>';}).join('')+'</ul></div></section>';
      html+='<section class="terminal-detail-section terminal-info-card terminal-conversation-section">'+detailSectionHeading('comments','SEGUIMIENTO','Conversación con el técnico','<span class="terminal-comment-count">'+comments.length+'</span>');
      html+='<div class="terminal-section-body">';
      if(comments.length){html+='<div id="terminalCommentHistory" class="terminal-comment-timeline">'+comments.map((c,index)=>'<article class="terminal-comment '+(c.is_private?'is-internal ':'')+(index<comments.length-1?'terminal-comment-older d-none':'')+'"><div class="terminal-comment-heading"><strong>'+esc(commenterLabel(c))+'</strong><time>'+esc(dateLabel(c.created_on||c.created_at))+'</time></div><span class="terminal-comment-visibility">'+(c.is_private?'Nota interna':'Respuesta pública')+'</span><p>'+esc(c.body||c.comment||'')+'</p>'+(c.attachments?.length?'<ul class="terminal-comment-files">'+c.attachments.map(f=>'<li><i class="fa fa-paperclip" aria-hidden="true"></i> '+(safeAttachmentUrl(f.url)?'<a href="'+esc(safeAttachmentUrl(f.url))+'" target="_blank" rel="noopener">'+esc(f.name)+'</a>':esc(f.name))+'</li>').join('')+'</ul>':'')+'</article>').join('')+'</div>';if(comments.length>1)html+='<button type="button" class="btn btn-sm btn-link terminal-conversation-toggle px-0" aria-expanded="false" aria-controls="terminalCommentHistory" data-count="'+(comments.length-1)+'">Mostrar más ('+(comments.length-1)+' anteriores)</button>';}
      else html+='<p class="terminal-empty-conversation">Aún no hay mensajes. Envía una nota para iniciar la conversación con el equipo técnico.</p>';
      html+='</div></section>';
      if(hist.length)html+='<section class="terminal-detail-section terminal-info-card terminal-activity-section">'+detailSectionHeading('history','TRAZABILIDAD','Actividad del ticket')+'<div class="terminal-section-body"><div class="terminal-state-history">'+hist.map(h=>'<div class="terminal-state-history-item"><strong><span>'+esc(stateLabel(h.estado_anterior||'Creado'))+'</span><i class="fa fa-arrow-right" aria-hidden="true"></i><span>'+esc(stateLabel(h.estado_nuevo))+'</span></strong><div class="terminal-history-meta"><time>'+esc(dateLabel(h.fecha_registro||h.fecha_estado_mojo))+'</time><span class="terminal-history-actor"><i class="fa fa-user-circle" aria-hidden="true"></i>'+esc(h.actor||h.usuario_correo||h.origen||'Autor no identificado')+'</span></div>'+(h.comentario?'<p>'+esc(h.comentario)+'</p>':'')+'</div>').join('')+'</div></div></section>';
      $('#ticketDetailBody').html(html); renderDetailActions(i);
    }).fail(x=>$('#ticketDetailBody').html('<div class="alert alert-danger mb-0">'+esc(x.responseJSON?.message||'No se pudo cargar el detalle del ticket.')+'</div>'));
  }
  function renderDetailActions(i){
    const state=i.state;let buttons='';
    if(state==='Solved')buttons+='<button type="button" class="btn btn-outline-primary" id="reopenTicket">Reabrir</button><button type="button" class="btn btn-outline-success" id="confirmCloseFromDetail">Cerrar ticket</button>';
    if(['Abierta','Reabierta','Solved'].includes(state)&&$('#ticketReplyForm').hasClass('d-none'))buttons+='<button type="button" class="btn btn-primary" id="showTicketReply" aria-expanded="false">'+($('#ticketReplyNoteId').val()?'Adjuntar archivos pendientes':'Responder al técnico')+'</button>';
    $('#ticketReplySubmit').text($('#ticketReplyNoteId').val()?'Reintentar adjuntos':(state==='Solved'?'Enviar y reabrir ticket':'Enviar al técnico'));
    $('#ticketDetailActions').html(buttons);
  }
  function renderResolvedModal(){
    if(!resolvedType)return;
    const list=$('#terminalResolvedList').empty(),solved=solvedFor(resolvedType);selectedCloseId=null;$('#terminalCloseConfirmation').addClass('d-none');$('#resolvedTypeLabel').text(types[resolvedType]?.label||resolvedType);
    if(!solved.length){list.append('<p class="text-muted mb-0">No hay tickets resueltos pendientes de cierre para este tipo.</p>');return;}
    solved.forEach(i=>list.append('<div class="terminal-resolved-ticket"><div><strong class="terminal-ticket-link">Ticket #'+Number(i.ticket_mojo_id)+'</strong><p class="mb-0">'+esc(i.descripcion)+'</p>'+(i.serial_urovo?'<small>Serie: '+esc(i.serial_urovo)+'</small>':'')+'</div><div class="d-flex flex-wrap gap-2"><button type="button" class="btn btn-sm btn-outline-primary view-ticket" data-id="'+Number(i.id)+'">Ver detalles</button><button type="button" class="btn btn-sm btn-outline-success select-resolved" data-id="'+Number(i.id)+'">Cerrar</button></div></div>'));
  }
  function selectResolved(id){const incident=solvedFor(resolvedType).find(i=>Number(i.id)===id);if(!incident)return;selectedCloseId=id;$('#terminalCloseTicket').text('#'+Number(incident.ticket_mojo_id));$('#terminalCloseConfirmation').removeClass('d-none');$('#confirmResolvedClose').trigger('focus');}
  function refresh(){
    let totalStock=0,totalDamaged=0,totalWorking=0,totalSolved=0;
    Object.keys(types).filter(type=>(Number(expected[type])||0)>0).forEach(type=>{const count=active.filter(i=>i.tipo_terminal===type&&statusOf(i)!=='Closed').length,solved=solvedFor(type).length,stock=Math.max(0,Number(expected[type])||0),working=Math.max(0,stock-count);totalStock+=stock;totalDamaged+=count;totalWorking+=working;totalSolved+=solved;$('[data-damaged="'+type+'"]').text(count);$('[data-working="'+type+'"]').text(working);$('[data-solved="'+type+'"]').text(solved).toggleClass('has-solved',solved>0);$('.show-resolved[data-type="'+type+'"]').prop('disabled',solved===0);$('.add-incident[data-type="'+type+'"]').prop('disabled',count>=stock);});
    $('#terminalStockTotal').text(totalStock);$('#terminalDamagedTotal').text(totalDamaged);$('#terminalWorkingTotal').text(totalWorking);$('#terminalSolvedTotal').text(totalSolved);
    const list=$('#terminalIncidentList').empty(),open=active.filter(i=>['Abierta','Reabierta'].includes(statusOf(i)));
    list.append('<h6>Abiertas</h6>');
    if(!open.length)list.append('<p class="text-muted">No hay incidencias abiertas.</p>');
    open.forEach(i=>list.append('<div class="terminal-incident active mb-2"><div><strong>'+esc(types[i.tipo_terminal]?.label||i.tipo_terminal)+'</strong> · <span class="terminal-ticket-link">#'+Number(i.ticket_mojo_id)+'</span> <span class="badge bg-warning text-dark">'+esc(statusOf(i))+'</span><div>'+esc(i.descripcion)+'</div></div><button type="button" class="btn btn-sm btn-outline-primary view-ticket" data-id="'+Number(i.id)+'">Ver ticket</button></div>'));
    renderResolvedModal();if(window.feather)feather.replace();
  }
  $('.add-incident').on('click',function(){const type=$(this).data('type');$('#terminalIncidentForm')[0].reset();$('#incidentType').val(type);$('#incidentTypeLabel').text(types[type].label);$('#urovoSerialField').toggleClass('d-none',type!=='urovo');$('#verifoneProblemField').toggleClass('d-none',type!=='verifone');$('.valera-fields').toggleClass('d-none',['urovo','verifone'].includes(type));requestKey=newRequestKey();modal.show();});
  $('#terminalIncidentForm').on('submit',function(e){e.preventDefault();const type=$('#incidentType').val(),description=$('#incidentDescription').val().trim(),serial=$('#urovoSerial').val().trim(),problem=type==='urovo'?'Terminal Urovo':$('#verifoneProblem').val(),button=$('#confirmIncident');if(!description){toastr.error('La descripción es obligatoria.');return;}if(type==='urovo'&&!serial){toastr.error('Capture el número de serie UROVO.');return;}if(type==='verifone'&&!problem){toastr.error('Seleccione un problema para la Verifone.');return;}if(!['urovo','verifone'].includes(type)&&(!$('#providerFolio').val().trim()||!$('#providerDate').val())){toastr.error('Capture folio y fecha del reporte al proveedor.');return;}button.prop('disabled',true).html('<span class="spinner-border spinner-border-sm me-2" role="status" aria-hidden="true"></span>Creando ticket…');$.post('/operations/terminal_ticket_create',{type,description,problem,provider_folio:$('#providerFolio').val().trim(),provider_date:$('#providerDate').val(),urovo_serial:serial,request_key:requestKey}).done(r=>{if(!r.success)return toastr.error(r.message||'No fue posible registrar la incidencia.');toastr.success('Incidencia registrada · Ticket #'+r.ticket_id);active.unshift(r.incident);modal.hide();refresh();requestKey=null;}).fail(x=>{let response=x.responseJSON;if(!response&&x.responseText){try{response=JSON.parse(x.responseText);}catch(e){response=null;}}const msg=response?.message||(x.status?'El servidor respondió con error HTTP '+x.status+'. La solicitud sigue abierta; puedes reintentar para conciliar el mismo ticket.':'No hubo respuesta del servidor. Conserva esta ventana abierta y reintenta para conciliar la misma solicitud.');toastr.error(msg);}).always(()=>button.prop('disabled',false).text('Crear ticket y registrar'));});
  $('.show-resolved').on('click',function(){resolvedType=$(this).data('type');renderResolvedModal();resolvedModal.show();});
  $('#terminalResolvedList').on('click','.select-resolved',function(){selectResolved(Number($(this).data('id')));});
  $('#terminalResolvedList').on('click','.view-ticket',function(){const id=Number($(this).data('id'));$('#terminalResolvedModal').one('hidden.bs.modal',()=>openDetail(id));resolvedModal.hide();});
  $('#terminalIncidentList').on('click','.view-ticket',function(){openDetail(Number($(this).data('id')));});
  $('#cancelResolvedClose').on('click',function(){selectedCloseId=null;$('#terminalCloseConfirmation').addClass('d-none');});
  function runAction(id,action,message,button){button.prop('disabled',true);const original=button.text();button.html('<span class="spinner-border spinner-border-sm me-2" aria-hidden="true"></span>'+(action==='close'?'Cerrando…':action==='reopen'?'Reabriendo…':'Enviando…'));const data=action==='reply'?new FormData():{incident_id:id,action};if(action==='reply'){data.append('incident_id',id);data.append('action',action);data.append('message',message||'');data.append('note_id',$('#ticketReplyNoteId').val()||'');Array.from($('#ticketReplyFiles')[0].files||[]).forEach(file=>data.append('attachments[]',file));}$.ajax({url:'/operations/terminal_incident_action',method:'POST',data,processData:action!=='reply',contentType:action==='reply'?false:'application/x-www-form-urlencoded'}).done(r=>{if(!r.success){toastr.error(r.message||'No se pudo completar la acción.');return;}if(action==='close'){active=active.filter(i=>Number(i.id)!==id);toastr.success('Ticket cerrado. La terminal ya no cuenta como dañada.');resolvedModal.hide();detailModal.hide();}else{const item=active.find(i=>Number(i.id)===id);if(item)item.estado_local=r.state;if(action==='reply'&&r.warnings?.length)r.warnings.forEach(warning=>toastr.warning(warning));else toastr.success(action==='reply'?(r.state==='Reabierta'?'Mensaje enviado al técnico y ticket reabierto.':'Mensaje enviado al técnico.'):'Ticket reabierto.');if(action==='reply')$('#ticketReplyForm')[0].reset();openDetail(id);if(action==='reply'&&r.note_id)$('#ticketReplyNoteId').val(r.note_id);}refresh();}).fail(x=>{const message=x.responseJSON?.message||'No fue posible completar la operación.';$('#ticketReplyError').removeClass('d-none').text(message);toastr.error(message);}).always(()=>button.prop('disabled',false).text(original));}
  $('#confirmResolvedClose').on('click',function(){const id=selectedCloseId;if(!id)return;runAction(id,'close','',$(this));});
  $('#ticketDetailActions').on('click','#reopenTicket',function(){runAction(Number(detailIncident?.id),'reopen','',$(this));});
  $('#ticketDetailActions').on('click','#confirmCloseFromDetail',function(){const i=detailIncident;if(!i)return;resolvedType=i.type;detailModal.hide();$('#terminalTicketDetailModal').one('hidden.bs.modal',()=>{renderResolvedModal();resolvedModal.show();setTimeout(()=>selectResolved(Number(i.id)),100);});});
  $('#ticketDetailActions').on('click','#showTicketReply',function(){const retry=!!$('#ticketReplyNoteId').val();$('#ticketReplyError').addClass('d-none').empty();$('#ticketReplyMode').toggleClass('d-none',!retry).text(retry?'El mensaje ya está en Mojo. Selecciona únicamente los archivos que faltaron.':'');$('#ticketReplyTitle').text(retry?'Adjuntar archivos pendientes':'Nuevo mensaje');$('#ticketReplyMessage').prop('disabled',retry);$('#ticketReplySubmit').text(retry?'Reintentar adjuntos':($('#ticketReplySubmit').text()));$('#ticketReplyForm').removeClass('d-none');$(this).remove();if(!retry)$('#ticketReplyMessage').trigger('focus');else $('#ticketReplyFiles').trigger('focus');$('#ticketReplyForm')[0].scrollIntoView({behavior:'smooth',block:'nearest'});});
  $('#ticketDetailBody').on('click','.terminal-conversation-toggle',function(){const expanded=$(this).attr('aria-expanded')==='true',count=Number($(this).data('count'))||0;$('#terminalCommentHistory .terminal-comment-older').toggleClass('d-none',expanded);$(this).attr('aria-expanded',String(!expanded)).text(expanded?'Mostrar más ('+count+' anteriores)':'Mostrar menos');});
  $('#ticketReplyFiles').on('change',function(){const files=Array.from(this.files||[]),bytes=files.reduce((total,file)=>total+file.size,0),allowed=['pdf','png','jpg','jpeg','webp','doc','docx','xls','xlsx','txt','csv'],invalid=files.some(file=>!allowed.includes(file.name.split('.').pop().toLowerCase()));$('#ticketReplyFileNames').text(files.length?files.map(file=>file.name+' ('+(file.size/1024/1024).toFixed(1)+' MB)').join(' · '):'Ningún archivo seleccionado.');$('#ticketReplyError').addClass('d-none').empty();if(invalid||files.length>5||files.some(file=>file.size>10*1024*1024)||bytes>25*1024*1024){$('#ticketReplyError').removeClass('d-none').text(invalid?'Elige PDF, imagen, Word, Excel, TXT o CSV.':'Elige hasta 5 archivos, máximo 10 MB por archivo y 25 MB en total.');this.value='';$('#ticketReplyFileNames').text('Ningún archivo seleccionado.');}});
  $('#ticketReplyMessage').on('paste',function(e){const clipboard=e.originalEvent.clipboardData;if(!clipboard)return;const images=Array.from(clipboard.items||[]).filter(item=>item.kind==='file'&&item.type.startsWith('image/')).map(item=>item.getAsFile()).filter(Boolean);if(!images.length)return;e.preventDefault();const input=$('#ticketReplyFiles')[0],existing=Array.from(input.files||[]),supported={'image/png':'png','image/jpeg':'jpg','image/webp':'webp'},stamp=new Date().toISOString().replace(/[-:.TZ]/g,''),pasted=images.map((image,index)=>{const ext=supported[image.type];return ext?new File([image],'captura-'+stamp+(images.length>1?'-'+(index+1):'')+'.'+ext,{type:image.type,lastModified:Date.now()}):null;});if(pasted.some(file=>!file)){ $('#ticketReplyError').removeClass('d-none').text('Por ahora puedes pegar capturas PNG, JPG o WEBP.');return;}const all=existing.concat(pasted),bytes=all.reduce((total,file)=>total+file.size,0);if(all.length>5||pasted.some(file=>file.size>10*1024*1024)||bytes>25*1024*1024){$('#ticketReplyError').removeClass('d-none').text('La captura supera el límite: máximo 5 archivos, 10 MB cada uno y 25 MB en total.');return;}const transfer=new DataTransfer();all.forEach(file=>transfer.items.add(file));input.files=transfer.files;$(input).trigger('change');});
  $('#ticketReplyCancel').on('click',function(){const noteId=$('#ticketReplyNoteId').val();$('#ticketReplyForm')[0].reset();$('#ticketReplyNoteId').val(noteId);$('#ticketReplyMessage').prop('disabled',!!noteId);$('#ticketReplyMode').addClass('d-none').empty();$('#ticketReplyFileNames').text('Ningún archivo seleccionado.');$('#ticketReplyError').addClass('d-none').empty();$('#ticketReplyForm').addClass('d-none');if(detailIncident){renderDetailActions({state:detailIncident.estado_local||detailIncident.estado_mojo||'Abierta'});$('#showTicketReply').trigger('focus');}});
  $('#ticketReplyForm').on('submit',function(e){e.preventDefault();const message=$('#ticketReplyMessage').val().trim(),files=$('#ticketReplyFiles')[0].files;if(!detailIncident)return;if(!message&&!files.length){$('#ticketReplyError').removeClass('d-none').text('Escribe un mensaje o adjunta al menos un archivo.');$('#ticketReplyMessage').trigger('focus');return;}$('#ticketReplyError').addClass('d-none').empty();runAction(Number(detailIncident.id),'reply',message,$(this).find('[type="submit"]'));});
  $('#terminalResolvedModal').on('hidden.bs.modal',function(){resolvedType=null;selectedCloseId=null;});
  refresh();
});
