$(function () {
  const app = $('#terminalInventoryApp'); if (!app.length) return;
  const types = JSON.parse(app.attr('data-types')); const active = JSON.parse(app.attr('data-active')); const staged = []; let previewedTicket=null;
  const modal = new bootstrap.Modal(document.getElementById('terminalIncidentModal'));
  const label = t => types[t].label;
  function activeCount(type){ return active.filter(i => i.tipo_terminal === type).length; }
  function stagedCount(type){ return staged.filter(i => i.type === type).length; }
  function refresh(){ let damaged=0, required=0; $('.terminal-count[data-field="damaged"]').each(function(){ const type=$(this).data('type'), amount=Number($(this).val())||0; damaged+=amount; const needed=Math.max(0,amount-activeCount(type)-stagedCount(type)); required+=needed; $('.add-incident[data-type="'+type+'"]').prop('disabled',needed===0); }); $('#terminalDamagedTotal').text(damaged); $('#terminalRequiredTotal').text(required); renderIncidents(); if(window.feather) feather.replace(); }
  function renderIncidents(){ const list=$('#incidentList').empty(); active.forEach(i=>list.append('<div class="terminal-incident active"><strong>'+label(i.tipo_terminal)+'</strong> · Ticket '+i.ticket_mojo_id+' <span class="badge bg-warning text-dark ms-2">Abierto</span><br><small>Incidencia activa; se conservará en este inventario.</small></div>')); staged.forEach((i,n)=>list.append('<div class="terminal-incident"><strong>'+label(i.type)+'</strong> · Ticket '+i.ticket_id+' <button type="button" class="btn btn-link btn-sm text-danger float-end remove-incident" data-index="'+n+'">Quitar</button><br><small>'+ $('<div>').text(i.description).html()+'</small></div>')); if(!active.length&&!staged.length) list.html('<p class="text-muted mb-0">Aún no hay incidencias vinculadas.</p>'); }
  $('.terminal-count').on('keydown',function(e){ if(['-','+','e','E','.'].includes(e.key)) e.preventDefault(); }).on('input',function(){ const value=Math.max(0,parseInt($(this).val(),10)||0); $(this).val(value); refresh(); }).on('blur',function(){ $(this).val(Math.max(0,parseInt($(this).val(),10)||0)); refresh(); });
  function showIncidentChoice(){ previewedTicket=null; $('#ticketPreview').addClass('d-none').empty(); $('#incidentChoice').removeClass('d-none'); $('#incidentFormFields').addClass('d-none'); $('#confirmIncident').addClass('d-none'); $('#incidentMode').val(''); }
  function showIncidentForm(mode){ const type=$('#incidentType').val(); previewedTicket=null; $('#ticketPreview').addClass('d-none').empty(); $('#incidentMode').val(mode); $('#incidentChoice').addClass('d-none'); $('#incidentFormFields').removeClass('d-none'); $('#confirmIncident').removeClass('d-none').text(mode==='create'?'Crear ticket y vincular':'Vincular ticket previsualizado'); $('.existing-ticket-field').toggle(mode==='existing'); $('#incidentDescriptionField').toggle(mode==='create'); $('.valera-field').toggle(type!=='urovo'&&mode==='create'); if(window.feather) feather.replace(); }
  $('.add-incident').on('click',function(){ const type=$(this).data('type'); $('#terminalIncidentForm')[0].reset(); $('#incidentType').val(type); $('#incidentTypeLabel').text(label(type)); $('#descriptionCount').text('0'); showIncidentChoice(); modal.show(); });
  $('#chooseCreateTicket').on('click',()=>showIncidentForm('create'));
  $('#chooseExistingTicket').on('click',()=>showIncidentForm('existing'));
  $('#backToIncidentChoice').on('click',showIncidentChoice);
  $('#incidentDescription').on('input',function(){$('#descriptionCount').text($(this).val().length);});
  $('#incidentList').on('click','.remove-incident',function(){staged.splice(Number($(this).data('index')),1);refresh();});
  function escapeHtml(value){return $('<div>').text(value||'').html();}
  function validateTicket(done){ const id=$('#incidentTicket').val().trim(),type=$('#incidentType').val(); if(!id){toastr.error('Capture el número de ticket Mojo.');return null;} return $.post('/operations/terminal_ticket_validate',{ticket_id:id,type:type}).done(r=>{if(r.success)done(Number(id),r.ticket,r.incident_data||{});else toastr.error(r.message);}).fail(x=>toastr.error(x.responseJSON?.message||'No se pudo validar el ticket.')); }
  $('#previewExistingTicket').on('click',function(){ const button=$(this); button.prop('disabled',true).text('Validando...'); const request=validateTicket((id,ticket,incidentData)=>{ previewedTicket={id:id,ticket:ticket,incidentData:incidentData}; const title=ticket.title||('Ticket Mojo '+id),description=incidentData.description||ticket.description||'Sin descripción disponible.',status=ticket.status||ticket.status_name||'Abierto'; let metadata=''; if($('#incidentType').val()!=='urovo') metadata='<div class="ticket-preview-meta mt-2"><span><strong>Tipo:</strong> '+escapeHtml(incidentData.type_terminal||'—')+'</span><span><strong>Folio:</strong> '+escapeHtml(incidentData.provider_folio||'—')+'</span><span><strong>Fecha:</strong> '+escapeHtml(incidentData.provider_date||'—')+'</span></div>'; $('#ticketPreview').html('<div class="ticket-preview"><div class="d-flex justify-content-between gap-2"><span class="ticket-preview-title">'+escapeHtml(title)+'</span><span class="badge bg-success">'+escapeHtml(status)+'</span></div><small class="text-muted d-block mt-1">Ticket Mojo #'+id+'</small><div class="ticket-preview-description mt-2">'+escapeHtml(description)+'</div>'+metadata+'</div>').removeClass('d-none'); toastr.success('Ticket validado. Los datos se tomarán directamente de Mojo.'); }); if(request) request.always(()=>button.prop('disabled',false).text('Validar y previsualizar')); else button.prop('disabled',false).text('Validar y previsualizar'); });
  $('#terminalIncidentForm').on('submit',function(e){e.preventDefault(); const type=$('#incidentType').val(),mode=$('#incidentMode').val(),description=$('#incidentDescription').val().trim(),button=$('#confirmIncident'); if(!mode){return;} if(mode==='create'&&(!description||description.length>250)){toastr.error('La descripción es obligatoria y no debe exceder 250 caracteres.');return;} if(mode==='create'&&type!=='urovo'&&(!$('#providerFolio').val().trim()||!$('#providerDate').val())){toastr.error('Capture folio y fecha de reporte al proveedor.');return;} const stage=(id,text,source)=>{staged.push({type:type,ticket_id:id,description:text,provider_folio:$('#providerFolio').val().trim(),provider_date:$('#providerDate').val(),source:source});modal.hide();refresh();}; if(mode==='existing'){ if(!previewedTicket||previewedTicket.id!==Number($('#incidentTicket').val())){toastr.warning('Primero valide y revise la previsualización del ticket.');return;} stage(previewedTicket.id,(previewedTicket.incidentData.description||previewedTicket.ticket.description||previewedTicket.ticket.title||('Ticket Mojo '+previewedTicket.id)).slice(0,250),'existing'); return; } button.prop('disabled',true).text('Creando ticket...'); $.post('/operations/terminal_ticket_create',{type:type,description:description,provider_folio:$('#providerFolio').val().trim(),provider_date:$('#providerDate').val()}).done(r=>{if(r.success&&r.ticket_id){toastr.success('Ticket Mojo creado y listo para vincular.');stage(Number(r.ticket_id),description,'create');}else toastr.error(r.message||'Mojo no devolvió un ticket.');}).fail(x=>toastr.error(x.responseJSON?.message||'No se pudo crear el ticket.')).always(()=>button.prop('disabled',false).text('Crear ticket y vincular'));});
  $('#terminalInventoryForm').on('submit',function(e){e.preventDefault(); const payload={details:{},new_incidents:staged}; $('.terminal-count').each(function(){const t=$(this).data('type'),field=$(this).data('field');payload.details[t]=payload.details[t]||{};payload.details[t][field]=$(this).val();}); const button=$('#saveTerminalInventory').prop('disabled',true).html('<span class="spinner-border spinner-border-sm"></span> Guardando...'); $.post('/operations/terminal_inventory_save',{payload:JSON.stringify(payload)}).done(r=>{if(r.success){toastr.success('Inventario guardado correctamente.');setTimeout(()=>location.reload(),700);}else{toastr.error(r.message);button.prop('disabled',false).html('<i data-feather="save"></i> Guardar inventario');}}).fail(x=>{toastr.error(x.responseJSON?.message||'No fue posible guardar el inventario.');button.prop('disabled',false).html('<i data-feather="save"></i> Guardar inventario');if(window.feather)feather.replace();}); });
  refresh();
});
